[package]
name = "stb_truetype_rust"
version = "2.27.0"
authors = ["StbRust Team"]
description = "Rust port of the stb_truetype"
repository = "https://github.com/StbRust/stb_truetype_rust"
keywords = ["truetype"]
license = "Unlicense"